# Generated by Django 5.2.1 on 2025-05-08 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AdminApp", "0002_customuseradmin"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUserAdmin",
        ),
    ]
