# Generated by Django 5.2.1 on 2025-05-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AdminApp", "0006_remove_report_screenshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="screenshot",
            field=models.ImageField(blank=True, null=True, upload_to="screenshots/"),
        ),
    ]
